apiVersion: apps/v1
kind: Deployment
metadata:
  name: Python-Application
  labels:
    app: pyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: python-app
        image: karnambhargava/python-application:latest
        ports:
        - containerPort: 5000
